
columns_to_use = [
    "draft_id",
    "pack_number",
    "pick_number",
    "pack_card_Abrade",
    "pack_card_Abyssal Harvester",
    "pack_card_Adventuring Gear",
    "pack_card_Aegis Turtle",
    "pack_card_Aetherize",
    "pack_card_Affectionate Indrik",
    "pack_card_Ajani's Pridemate",
    "pack_card_Ajani, Caller of the Pride",
    "pack_card_Akroma's Memorial",
    "pack_card_Alesha, Who Laughs at Fate",
    "pack_card_Ambush Wolf",
    "pack_card_An Offer You Can't Refuse",
    "pack_card_Angel of Finality",
    "pack_card_Anthem of Champions",
    "pack_card_Apothecary Stomper",
    "pack_card_Arahbo, the First Fang",
    "pack_card_Arbiter of Woe",
    "pack_card_Arcane Epiphany",
    "pack_card_Archmage of Runes",
    "pack_card_Armasaur Guide",
    "pack_card_Ashroot Animist",
    "pack_card_Authority of the Consuls",
    "pack_card_Axgard Cavalry",
    "pack_card_Bake into a Pie",
    "pack_card_Balmor, Battlemage Captain",
    "pack_card_Banishing Light",
    "pack_card_Banner of Kinship",
    "pack_card_Battlesong Berserker",
    "pack_card_Beast-Kin Ranger",
    "pack_card_Bigfin Bouncer",
    "pack_card_Billowing Shriekmass",
    "pack_card_Bite Down",
    "pack_card_Blanchwood Armor",
    "pack_card_Blasphemous Edict",
    "pack_card_Bloodfell Caves",
    "pack_card_Bloodthirsty Conqueror",
    "pack_card_Bloom Tender",
    "pack_card_Blossoming Sands",
    "pack_card_Boltwave",
    "pack_card_Brass's Bounty",
    "pack_card_Brazen Scourge",
    "pack_card_Brineborn Cutthroat",
    "pack_card_Broken Wings",
    "pack_card_Bulk Up",
    "pack_card_Burglar Rat",
    "pack_card_Burnished Hart",
    "pack_card_Burst Lightning",
    "pack_card_Bushwhack",
    "pack_card_Cackling Prowler",
    "pack_card_Campus Guide",
    "pack_card_Cat Collector",
    "pack_card_Cathar Commando",
    "pack_card_Celestial Armor",
    "pack_card_Cephalid Inkmage",
    "pack_card_Chandra, Flameshaper",
    "pack_card_Claws Out",
    "pack_card_Clinquant Skymage",
    "pack_card_Condemn",
    "pack_card_Consuming Aberration",
    "pack_card_Courageous Goblin",
    "pack_card_Crackling Cyclops",
    "pack_card_Crypt Feaster",
    "pack_card_Crystal Barricade",
    "pack_card_Curator of Destinies",
    "pack_card_Dauntless Veteran",
    "pack_card_Day of Judgment",
    "pack_card_Dazzling Angel",
    "pack_card_Diregraf Ghoul",
    "pack_card_Dismal Backwater",
    "pack_card_Divine Resilience",
    "pack_card_Doubling Season",
    "pack_card_Dragon Trainer",
    "pack_card_Drake Hatcher",
    "pack_card_Drakuseth, Maw of Flames",
    "pack_card_Dreadwing Scavenger",
    "pack_card_Dwynen's Elite",
    "pack_card_Dwynen, Gilt-Leaf Daen",
    "pack_card_Eager Trufflesnout",
    "pack_card_Eaten Alive",
    "pack_card_Electroduplicate",
    "pack_card_Elementalist Adept",
    "pack_card_Elenda, Saint of Dusk",
    "pack_card_Elfsworn Giant",
    "pack_card_Elvish Archdruid",
    "pack_card_Elvish Regrower",
    "pack_card_Embercleave",
    "pack_card_Empyrean Eagle",
    "pack_card_Erudite Wizard",
    "pack_card_Essence Scatter",
    "pack_card_Etali, Primal Storm",
    "pack_card_Evolving Wilds",
    "pack_card_Exemplar of Light",
    "pack_card_Exsanguinate",
    "pack_card_Extravagant Replication",
    "pack_card_Faebloom Trick",
    "pack_card_Fake Your Own Death",
    "pack_card_Fanatical Firebrand",
    "pack_card_Felidar Savior",
    "pack_card_Felling Blow",
    "pack_card_Fiend Artisan",
    "pack_card_Fiendish Panda",
    "pack_card_Fiery Annihilation",
    "pack_card_Firebrand Archer",
    "pack_card_Firespitter Whelp",
    "pack_card_Fishing Pole",
    "pack_card_Flamewake Phoenix",
    "pack_card_Fleeting Distraction",
    "pack_card_Fleeting Flight",
    "pack_card_Forest",
    "pack_card_Frenzied Goblin",
    "pack_card_Garruk's Uprising",
    "pack_card_Genesis Wave",
    "pack_card_Ghalta, Primal Hunger",
    "pack_card_Giada, Font of Hope",
    "pack_card_Giant Growth",
    "pack_card_Gleaming Barrier",
    "pack_card_Gnarlid Colony",
    "pack_card_Goblin Boarders",
    "pack_card_Goblin Bushwhacker",
    "pack_card_Goblin Negotiation",
    "pack_card_Goblin Surprise",
    "pack_card_Goldvein Pick",
    "pack_card_Good-Fortune Unicorn",
    "pack_card_Gorehorn Raider",
    "pack_card_Grappling Kraken",
    "pack_card_Grim Tutor",
    "pack_card_Grow from the Ashes",
    "pack_card_Guarded Heir",
    "pack_card_Gutless Plunderer",
    "pack_card_Hare Apparent",
    "pack_card_Healer's Hawk",
    "pack_card_Heartfire Immolator",
    "pack_card_Helpful Hunter",
    "pack_card_Herald of Eternal Dawn",
    "pack_card_Heraldic Banner",
    "pack_card_Hero's Downfall",
    "pack_card_Heroic Reinforcements",
    "pack_card_Hidetsugu's Second Rite",
    "pack_card_High Fae Trickster",
    "pack_card_High-Society Hunter",
    "pack_card_Homunculus Horde",
    "pack_card_Hungry Ghoul",
    "pack_card_Icewind Elemental",
    "pack_card_Imprisoned in the Moon",
    "pack_card_Incinerating Blast",
    "pack_card_Infernal Vessel",
    "pack_card_Infestation Sage",
    "pack_card_Inspiration from Beyond",
    "pack_card_Inspiring Call",
    "pack_card_Inspiring Paladin",
    "pack_card_Involuntary Employment",
    "pack_card_Island",
    "pack_card_Joust Through",
    "pack_card_Juggernaut",
    "pack_card_Jungle Hollow",
    "pack_card_Kaito, Cunning Infiltrator",
    "pack_card_Kellan, Planar Trailblazer",
    "pack_card_Kiora, the Rising Tide",
    "pack_card_Koma, World-Eater",
    "pack_card_Krenko, Mob Boss",
    "pack_card_Kykar, Zephyr Awakener",
    "pack_card_Lathril, Blade of the Elves",
    "pack_card_Leyline Axe",
    "pack_card_Lightshell Duo",
    "pack_card_Liliana, Dreadhorde General",
    "pack_card_Llanowar Elves",
    "pack_card_Loot, Exuberant Explorer",
    "pack_card_Luminous Rebuke",
    "pack_card_Lunar Insight",
    "pack_card_Macabre Waltz",
    "pack_card_Make Your Move",
    "pack_card_Marauding Blight-Priest",
    "pack_card_Meteor Golem",
    "pack_card_Micromancer",
    "pack_card_Midnight Snack",
    "pack_card_Mild-Mannered Librarian",
    "pack_card_Mischievous Mystic",
    "pack_card_Mischievous Pup",
    "pack_card_Mocking Sprite",
    "pack_card_Mossborn Hydra",
    "pack_card_Mountain",
    "pack_card_Muldrotha, the Gravetide",
    "pack_card_Needletooth Pack",
    "pack_card_Nessian Hornbeetle",
    "pack_card_Nine-Lives Familiar",
    "pack_card_Niv-Mizzet, Visionary",
    "pack_card_Omniscience",
    "pack_card_Overrun",
    "pack_card_Painful Quandary",
    "pack_card_Paradise Druid",
    "pack_card_Perforating Artist",
    "pack_card_Phyrexian Arena",
    "pack_card_Pilfer",
    "pack_card_Plains",
    "pack_card_Preposterous Proportions",
    "pack_card_Prideful Parent",
    "pack_card_Progenitus",
    "pack_card_Quakestrider Ceratops",
    "pack_card_Quick-Draw Katana",
    "pack_card_Quilled Greatwurm",
    "pack_card_Raise the Past",
    "pack_card_Ravenous Amulet",
    "pack_card_Reassembling Skeleton",
    "pack_card_Reclamation Sage",
    "pack_card_Refute",
    "pack_card_Resolute Reinforcements",
    "pack_card_Revenge of the Rats",
    "pack_card_Rise of the Dark Realms",
    "pack_card_Rite of the Dragoncaller",
    "pack_card_Rogue's Passage",
    "pack_card_Ruby, Daring Tracker",
    "pack_card_Rugged Highlands",
    "pack_card_Run Away Together",
    "pack_card_Rune-Scarred Demon",
    "pack_card_Rune-Sealed Wall",
    "pack_card_Sanguine Syphoner",
    "pack_card_Savannah Lions",
    "pack_card_Scavenging Ooze",
    "pack_card_Scoured Barrens",
    "pack_card_Scrawling Crawler",
    "pack_card_Searslicer Goblin",
    "pack_card_Secluded Courtyard",
    "pack_card_Seeker's Folly",
    "pack_card_Seismic Rupture",
    "pack_card_Self-Reflection",
    "pack_card_Serra Angel",
    "pack_card_Shivan Dragon",
    "pack_card_Sire of Seven Deaths",
    "pack_card_Skyknight Squire",
    "pack_card_Skyship Buccaneer",
    "pack_card_Slagstorm",
    "pack_card_Slumbering Cerberus",
    "pack_card_Snakeskin Veil",
    "pack_card_Solemn Simulacrum",
    "pack_card_Soul-Shackled Zombie",
    "pack_card_Soulstone Sanctuary",
    "pack_card_Sower of Chaos",
    "pack_card_Spectral Sailor",
    "pack_card_Sphinx of Forgotten Lore",
    "pack_card_Sphinx's Tutelage",
    "pack_card_Spinner of Souls",
    "pack_card_Spitfire Lagac",
    "pack_card_Squad Rallier",
    "pack_card_Stab",
    "pack_card_Strix Lookout",
    "pack_card_Stroke of Midnight",
    "pack_card_Stromkirk Bloodthief",
    "pack_card_Strongbox Raider",
    "pack_card_Sun-Blessed Healer",
    "pack_card_Sure Strike",
    "pack_card_Swamp",
    "pack_card_Swiftblade Vindicator",
    "pack_card_Swiftfoot Boots",
    "pack_card_Swiftwater Cliffs",
    "pack_card_Sylvan Scavenging",
    "pack_card_Tatyova, Benthic Druid",
    "pack_card_Temporal Manipulation",
    "pack_card_Think Twice",
    "pack_card_Thornwood Falls",
    "pack_card_Thousand-Year Storm",
    "pack_card_Thrill of Possibility",
    "pack_card_Time Stop",
    "pack_card_Tinybones, Bauble Burglar",
    "pack_card_Tolarian Terror",
    "pack_card_Tragic Banshee",
    "pack_card_Tranquil Cove",
    "pack_card_Treetop Snarespinner",
    "pack_card_Twinblade Blessing",
    "pack_card_Twinflame Tyrant",
    "pack_card_Uncharted Voyage",
    "pack_card_Valkyrie's Call",
    "pack_card_Vampire Gourmand",
    "pack_card_Vampire Nighthawk",
    "pack_card_Vampire Soulcaller",
    "pack_card_Vanguard Seraph",
    "pack_card_Vengeful Bloodwitch",
    "pack_card_Vivien Reid",
    "pack_card_Wardens of the Cycle",
    "pack_card_Wary Thespian",
    "pack_card_Wildwood Scourge",
    "pack_card_Wind-Scarred Crag",
    "pack_card_Witness Protection",
    "pack_card_Youthful Valkyrie",
    "pack_card_Zimone, Paradox Sculptor",
    "pack_card_Zombify",
    "pack_card_Zul Ashur, Lich Lord",
]